### ISSUE TITLE
Appearance file seems to generate errors in the Gaussian Distribution generator (need to check)

### ISSUE THREAD

**Issue by pinosante** [pinosante/VAM-Evolutionary-Character-Creation#10]
Using random samples from multivariate gaussian distribution for initialization.
Source files: Choose All Appearances (11 Files)
** On entry to DLASCLS parameter number 4 had an illegal value
** On entry to DLASCLS parameter number 4 had an illegal value
Exception in Tkinter callback
Traceback (most recent call last):
File "C:\Python38\lib\tkinter\__init__.py", line 1892, in __call__
File "VAM Evolutionary Character Creation.py", line 757, in <lambda>
File "VAM Evolutionary Character Creation.py", line 1252, in generate_next_population
File "VAM Evolutionary Character Creation.py", line 1621, in gaussian_initialize_population
File "_generator.pyx", line 3508, in numpy.random._generator.Generator.multivariate_normal
File "<__array_function__ internals>", line 5, in svd
File "C:\Python38\lib
[Troublesome Appearance for Gaussian Generator for Evolutionary Character App.zip](https://github.com/pinosante/VAM-Evolutionary-Character-Creation/files/10526860/Troublesome.Appearance.for.Gaussian.Generator.for.Evolutionary.Character.App.zip)
\site-packages\numpy\linalg\linalg.py", line 1661, in svd
File "C:\Python38\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_svd_nonconvergence
numpy.linalg.LinAlgError: SVD did not converge

I've found that when I select specific files that I don't run into any issues. I don't want to be a pest but thought I'd share the error message I got as an FYI.

Attached: file which should generate this error when included

**Comment by chris-b-pacon** [comment]
Open the Vap file with a text editor (suggestiong Notepad++) and look for this line:

               "value" : "NaN"

In the editor, remove the complete morph or set it to 0.0 testwise and try if this changes the behavior. I did not test it, but can imagine that a not-a-number may be fatal.

By the way, your line numbers a different from the line numbers in the main branch. This causes problems when talking about the code. Also, are you wokring on the main bracnh? PLease don't because this will cause conflicts as soon as we merge my changes from my wroking branch.

**Comment by pinosante** [comment]
Good find! Yeah those NaNs need to be checked for and set to 0 or the appearance file rejected.

I'm not working on the main branch because I figured that would mess up your refactoring :).

I think the user who mentioned this bug hasn't updated to the last version of the app, and then explains the different line numbers.

**Comment by chris-b-pacon** [comment]
At least we should implement a validation that checks if there are any NaNs and handles them by ignoring or some other solution to make the app more stable.

**Comment by chris-b-pacon** [comment]
> I'm not working on the main branch because I figured that would mess up your refactoring :).

Highly appreciated! Please find the time to check out my changes  from my branch by testing them and giving me feedback on any flaws. This is a structural change and should be merged before we go on with other issues -- would create too much conflcihts otherwise. Shall I create a pull request?

**Comment by chris-b-pacon** [comment]
Should be fixed after merging into main.
