### ISSUE TITLE
Suggestion: Option to change the number of rated appearances

### ISSUE THREAD

**Issue by chris-b-pacon** [pinosante/VAM-Evolutionary-Character-Creation#13]
### Description
Could be nice to change the number of appearances to rate in VAM. So insted of 20, provide just 5. But I don't have the slightest idea if this is viable for the algorithm.

**Comment by pinosante** [comment]
I wouldn't recommend that. The algorithm needs a large gene pool to be effective. By allowing users to change this hyper parameter they can basically make the app stop functioning properly. What happens, if you use only 5 available appearances, is that you create an 'echo chamber' of the most popular appearances and after a few generations, there is nothing to improve upon using different genes from other appearances. It would actually probably be even better to have more than 20 appearances, but that is very hard (boring even) for the user to rate.

**Comment by chris-b-pacon** [comment]
> I wouldn't recommend that. The algorithm needs a large gene pool to be effective. By allowing users to change this hyper parameter they can basically make the app stop functioning properly. What happens, if you use only 5 available appearances, is that you create an 'echo chamber' of the most popular appearances and after a few generations, there is nothing to improve upon using different genes from other appearances. It would actually probably be even better to have more than 20 appearances, but that is very hard (boring even) for the user to rate.

I see and understand. I already assumed that this could cause problems. I am closing this issue now.

**Comment by chris-b-pacon** [comment]
This idea is not feasible because of the genetic algorithm's requirements of a minimum population.
