### ISSUE TITLE
App breaks when trying to load a thumbnail file which is empty (0 bytes)

### ISSUE THREAD

**Issue by pinosante** [pinosante/VAM-Evolutionary-Character-Creation#14]
`    image = Image.open(thumbnailpath)
  File "C:\Users\Charlie\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 3030, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Games\\VaM 1.19 `Clean\\Custom\\Atom\\Person\\Appearance\\PresetMaker\\ShinySheep\\Preset_SportsGirl-Female.jpg'``

This happens in the method get_thumbnail_for_filename

**Comment by chris-b-pacon** [comment]
Can that be reproduced by chosing a template in the GUI?

**Comment by pinosante** [comment]
Before you even get to the template choosing, the app will have crashed when trying to read all the appearance files from the given appearance files directory.

**Comment by pinosante** [comment]
I tried to upload the empty file, but github wouldn't let me add empty files :). But you can download this zipfile which contains an empty image. Just unzip this anywhere in your appearance folder and try to run the app. It will break.
[Example of empty preset image.zip](https://github.com/pinosante/VAM-Evolutionary-Character-Creation/files/10527289/Example.of.empty.preset.image.zip)

**Comment by chris-b-pacon** [comment]
I saw that there is already a handling for a missing jpg file. I catch the exception in case size 0 and use the "no_thumbnail.jpg" instead. This is also printed. Work fine, you can merge.
