### ISSUE TITLE
Consider to open issue creation to VAM community

### ISSUE THREAD

**Issue by chris-b-pacon** [pinosante/VAM-Evolutionary-Character-Creation#31]
I read the discussion on the Hub and recognized there where many issues which could be posted here in Github.

Would it be clever to ask the community to create issues here? I don't know.

**Comment by pinosante** [comment]
I think that adds another burden to the users and I'd try to avoid that. Some of the users aren't that technical oriented (although they choose VAM as software) so I don't mind checking the vam hub and moving some of the issues to this place.

**Comment by chris-b-pacon** [comment]
Agreed.
