### ISSUE TITLE
In VAM another button to reconnect with app

### ISSUE THREAD

**Issue by chris-b-pacon** [pinosante/VAM-Evolutionary-Character-Creation#46]
Useful during testing to prevent reloading the scene again and again after problems with the app.

**Comment by pinosante** [comment]
I don't get this? What is the feature, and when is it handy? What is the problem without this feature?

**Comment by chris-b-pacon** [comment]
Trying to explain...

The VAM scene does not notice if the Python app has terminated, i.e. by hitting a bug. At the moment the only solution to return to a clear state in VAM is to reload the scene, because there is no obvious option to reset communication to Python. An additional button in VAM for reconnection would be nice, especially for me, causing crashes all the time while testing. :)

BTW: I am not sure, but sometimes the VAM scene seems to notice that the app is down, and will reset itself, but I wasn't able to reproduce that.

Is there already a feature to reconnect in case of connection lost and it works now and then? Testing it right now, after I closed the app via 'X', but nothing happens.

**Comment by chris-b-pacon** [comment]
After some more testing I noticed that VAM seems to recognize lost connection, if I click one of the rating buttons inside the scene. That's very useful and may solve my problem. :)

**Comment by chris-b-pacon** [comment]
Yeah, seems to work fine for me -- disregard my complains, going to close the ticket! :)
