### ISSUE TITLE
Separate program into several modules

### ISSUE THREAD

**Issue by chris-b-pacon** [pinosante/VAM-Evolutionary-Character-Creation#7]
Some ideas:

- mandatory
  - **GUI** (Window handling)
  - **BL (Business Logic)**  (Genetic algorithms and so on) 
  - App (launches GUI and BL)
- optional
  - Communication (with VAM)
  - File access 
  - Utilities

I suggest that I create a feature branch to implement a working version with a first separation into GUI, BL, and App. You can then see the results and decide to merge it into the main branch.

**Comment by chris-b-pacon** [comment]
I suggest that you pull my branch and test what I have done. If you are pleased with it, we can merge it into the master. Doing this early will help to prevent conflicts later, but of course I am not sure if there are still parts of it which won't work because of my changes.

If you prefer, I will create pull request to merge my stuff into main. In other Git systems this will give you a chance to examine my changes and review them here on Github. Sorry if this sounds complicated -- I fully understand, because at my company we chagned to this work flow recently and I pity my colleagues who are not used to it. But in the end it works surpisingly well.

**Comment by pinosante** [comment]
I just ran it and it looks good! I haven't delved into the code yet to look for errors, but the app is running fine it seems.
