### ISSUE TITLE
Improve error handling so it shows filename for the file with the incorrect bytecode (or find a workaround to still read the file)

### ISSUE THREAD

**Issue by pinosante** [pinosante/VAM-Evolutionary-Character-Creation#9]
![image](https://user-images.githubusercontent.com/39878663/215255261-a1527e02-9f71-40d9-91db-185b6e9b5eda.png)

**Comment by chris-b-pacon** [comment]
How to reproduce this behavior?

**Comment by pinosante** [comment]
First fix the error handling then ask the user to upload the faulty file.

**Comment by chris-b-pacon** [comment]
> First fix the error handling then ask the user to upload the faulty file.

Sorry, I don't get it. How can anyone make the app behave like this, so I or someone else can debug it? Do I need some files which reproduce the problem when loading them? Maybe a step-by-step documentaion would be helpfule -- this is what I normally add to my tickets under the headline "How to reproduce".

**Comment by pinosante** [comment]
This bug came from a user from the hub. It's hard to reproduce for this user, since it is unknown which of the appearance files generates this bug. So in order for the user to even share the file which creates this bug, the error handling should be improved to write out the name of the buggy appearance files. After that update, and if the user is willing, the user can upload the faulty appearance file. That would need to be asked on the hub, after this error handling is fixed.

**Comment by chris-b-pacon** [comment]
> > First fix the error handling then ask the user to upload the faulty file.
> 
> Sorry, I don't get it. How can anyone make the app behave like this, so I or someone else can debug it? Do I need some files which reproduce the problem when loading them? Maybe a step-by-step documentaion would be helpfule -- this is what I normally add to my tickets under the headline "How to reproduce".



> This bug came from a user from the hub. It's hard to reproduce for this user, since it is unknown which of the appearance files generates this bug. So in order for the user to even share the file which creates this bug, the error handling should be improved to write out the name of the buggy appearance files. After that update, and if the user is willing, the user can upload the faulty appearance file. That would need to be asked on the hub, after this error handling is fixed.

I see. Going think about it.
